
package com.senior.g5.doug;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "g5-senior-services", targetNamespace = "http://services.senior.com.br", wsdlLocation = "http://snrsj:8080/g5-senior-services/sapiens_Synccom.senior.g5.doug?wsdl")
public class G5SeniorServices
    extends Service
{

    private static final URL G5SENIORSERVICES_WSDL_LOCATION;
    private static final WebServiceException G5SENIORSERVICES_EXCEPTION;
    private static final QName G5SENIORSERVICES_QNAME = new QName("http://services.senior.com.br", "g5-senior-services");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://snrsj:8080/g5-senior-services/sapiens_Synccom.senior.g5.doug?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        G5SENIORSERVICES_WSDL_LOCATION = url;
        G5SENIORSERVICES_EXCEPTION = e;
    }

    public G5SeniorServices() {
        super(__getWsdlLocation(), G5SENIORSERVICES_QNAME);
    }

    public G5SeniorServices(WebServiceFeature... features) {
        super(__getWsdlLocation(), G5SENIORSERVICES_QNAME, features);
    }

    public G5SeniorServices(URL wsdlLocation) {
        super(wsdlLocation, G5SENIORSERVICES_QNAME);
    }

    public G5SeniorServices(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, G5SENIORSERVICES_QNAME, features);
    }

    public G5SeniorServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public G5SeniorServices(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SapiensSynccomSeniorG5Doug
     */
    @WebEndpoint(name = "sapiens_Synccom.senior.g5.dougPort")
    public SapiensSynccomSeniorG5Doug getSapiensSynccomSeniorG5DougPort() {
        return super.getPort(new QName("http://services.senior.com.br", "sapiens_Synccom.senior.g5.dougPort"), SapiensSynccomSeniorG5Doug.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SapiensSynccomSeniorG5Doug
     */
    @WebEndpoint(name = "sapiens_Synccom.senior.g5.dougPort")
    public SapiensSynccomSeniorG5Doug getSapiensSynccomSeniorG5DougPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.senior.com.br", "sapiens_Synccom.senior.g5.dougPort"), SapiensSynccomSeniorG5Doug.class, features);
    }

    private static URL __getWsdlLocation() {
        if (G5SENIORSERVICES_EXCEPTION!= null) {
            throw G5SENIORSERVICES_EXCEPTION;
        }
        return G5SENIORSERVICES_WSDL_LOCATION;
    }

}
