
package com.senior.g5.doug;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "sapiens_Synccom.senior.g5.doug", targetNamespace = "http://services.senior.com.br")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SapiensSynccomSeniorG5Doug {


    /**
     * 
     * @param encryption
     * @param parameters
     * @param password
     * @param user
     * @return
     *     returns com.senior.g5.doug.SynccomSeniorG5DougSomaOut
     */
    @WebMethod(operationName = "Soma")
    @WebResult(name = "result", partName = "result")
    @Action(input = "http://services.senior.com.br/sapiens_Synccom.senior.g5.doug/SomaRequest", output = "http://services.senior.com.br/sapiens_Synccom.senior.g5.doug/SomaResponse")
    public SynccomSeniorG5DougSomaOut soma(
        @WebParam(name = "user", partName = "user")
        String user,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "encryption", partName = "encryption")
        int encryption,
        @WebParam(name = "parameters", partName = "parameters")
        SynccomSeniorG5DougSomaIn parameters);

}
